#!/bin/bash
#  Script Name: htpasswd-gui
#  Usage: ./htpasswd-gui
#  Written By: Alon Shafir , August-2022
#  Description: GUI for htpasswd


host=$(hostname)

#htfile='/DATA/NginxConf/.htpasswd'

function reload() {
userarr=$( cat /DATA/NginxConf/.htpasswd| cut -d ":" -f1)
for i in ${!userarr[*]};
  do
     echo -e "${userarr[$i]}" > users
done
}
export -f reload


function update() {
  if [ -f users ]
     then
     sleep 0.1
   else
     touch users
   fi
echo -e '\f'
cat users

while inotifywait -e modify users;
  do
#  sum1=$(cat sum)
#  sum2=$(shasum 666 | cut -d " " -f1)

#if [ "$sum1" != "$sum2" ]
#    then
      echo -e '\f'
  cat users
#    echo $sum2 > sum
#  else
#    sleep 0.5
#  fi

done
}
 export -f update



function listing(){
 if [ -f tmp ]
    then
    sleep 0.1
  else
    touch tmp
  fi
update  | yad --title=Users@$host --geometry=300x500   --button="Add user":"bash -c add"   --select-action='bash -c "echo %s > tmp " '  --button="Remove user":"bash -c del" --button="Exit":"bash -c exit" --listen --list  --column=Users\

}
export -f listing



function del() {
user=$(cat tmp)
htpasswd -D /DATA/NginxConf/.htpasswd $user
reload
}
export -f del



function add() {
credentials=$(yad --form --title="Add user"\
           --field="Username"\
            --field="Password:H"\
            --width=350  --button="Add":2 --button="Cancel":1  --buttons-layout=center)
 if [[ $? -eq 2 ]];
  then
    user=$(echo $credentials | cut -d '|' -f 1)
    pass=$(echo $credentials | cut -d '|' -f 2)
    htpasswd -b  /DATA/NginxConf/.htpasswd $user $pass

  elif [[ $? -eq 1 ]];
    then
      sleep 0.1
fi

reload

}
export -f add


function exit() {
pids=$(ps ax | egrep 'htgui|yad' | cut -d " " -f1)
kill -9 $pids
}
export -f exit


#function exit1() {
#bpid=$(ps ax | grep htgui | cut -d " " -f1 | head -n1)
#ypid=$(ps ax | grep yad | cut -d " " -f1 | head -n1)


#if [ "$ypid" != "$ypid" ]
#then
  #kill -9 $bpid
#else
#  sleep 0.5
#fi
#}
#export -f exit1




bash -c   reload&&listing
