#!/bin/bash
host=$(hostname)

function ls(){
 if [ -f tmp ]
    then
    sleep 1
  else
    touch tmp
  fi
#list=$(   )
userarr=$( cat /DATA/NginxConf/.htpasswd | cut -d ":" -f1)
for i in ${!userarr[*]};
  do
  si=${userarr[$i]}
done
  yad --title=Users$host --geometry=400x400 --button="Add user":"bash -c add"   --select-action='bash -c "echo %s > tmp " '  --button="Remove user":"bash -c del" --listen --list  --column=Users\
  $si
}
export -f ls



function del() {
us=$(cat tmp)
htpasswd -D /DATA/NginxConf/.htpasswd $us
}
export -f del



function add() {
credentials=$(yad --form --title="Add user"\
           --field="Username"\
            --field="Password:H"\
            --width=350  --button="Add":2 --button="Cancel":1  --buttons-layout=center)
 if [[ $? -eq 2 ]];
  then
    user=$(echo $credentials | cut -d '|' -f 1)
    pass=$(echo $credentials | cut -d '|' -f 2)
    htpasswd -b  /DATA/NginxConf/.htpasswd $user $pass

  elif [[ $? -eq 1 ]];
    then
      exit 0
fi


}
export -f add



bash -c ls
#yad --geometry=200x50 --button=Users:"bash -c ls"
